package main

const INVALID_TAG_CONSTRAINT_EXPRESSION = 100

const GITHUB_REPO_URL_MALFORMED_OR_NOT_PARSEABLE = 300

const INVALID_GITHUB_TOKEN_OR_ACCESS_DENIED = 401
const REPO_DOES_NOT_EXIST_OR_ACCESS_DENIED = 404

const FAILED_TO_DOWNLOAD_FILE = 500

const VARYING_LIST_SIZES_OF_RELEASE_ASSETS_CHECKSUMS_AND_ALGOS = 501
const UNSUPPORTED_CHECKSUM_ALGO = 502
const CHECKSUM_DOES_NOT_MATCH = 503
const ERROR_WHILE_COMPUTING_CHECKSUM = 504
