package main

const INVALID_TAG_CONSTRAINT_EXPRESSION = 100

const GITHUB_REPO_URL_MALFORMED_OR_NOT_PARSEABLE = 300

const INVALID_GITHUB_TOKEN_OR_ACCESS_DENIED = 401
const REPO_DOES_NOT_EXIST_OR_ACCESS_DENIED = 404
const FAILED_TO_DOWNLOAD_FILE_HEADER = 500
const FAILED_TO_DOWNLOAD_FILE = 500
const CHECKSUM_DOES_NOT_MATCH = 510
const ERROR_WHILE_COMPUTING_CHECKSUM = 520
